#!/usr/bin/env python3
"""
Yandex m3u8 Extractor - Extract video streams from Yandex.Disk
"""

import requests
import re
import sys
from datetime import datetime

def extract_from_yandex(url):
    """Extract video links from Yandex.Disk public link"""
    print(f"🔍 Extracting from: {url}")
    
    try:
        # Extract public key from Yandex.Disk URL
        if 'yadi.sk' in url:
            # Follow redirects to get the full URL
            response = requests.get(url, allow_redirects=True)
            print(f"  📍 Redirected to: {response.url}")
            
            # Extract public key
            public_key_match = re.search(r'/d/([^/?]+)', response.url)
            if public_key_match:
                public_key = public_key_match.group(1)
                print(f"  🔑 Public key: {public_key}")
            else:
                print("❌ Could not extract public key")
                return []
        else:
            print("❌ Not a valid Yandex.Disk URL")
            return []
        
        # Get file list from Yandex.Disk API
        api_url = f"https://cloud-api.yandex.net/v1/disk/public/resources?public_key={public_key}"
        print(f"  📡 Fetching file list...")
        
        response = requests.get(api_url)
        if response.status_code != 200:
            print(f"❌ API error: {response.status_code}")
            return []
        
        data = response.json()
        videos = []
        
        # Process files
        if '_embedded' in data and 'items' in data['_embedded']:
            items = data['_embedded']['items']
            print(f"  📁 Found {len(items)} items")
            
            for item in items:
                if item['type'] == 'file':
                    filename = item['name']
                    # Check if it's a video file
                    if filename.lower().endswith(('.mp4', '.mkv', '.avi', '.mov', '.webm')):
                        print(f"  🎥 Found video: {filename}")
                        
                        # Get download URL
                        download_url = f"https://cloud-api.yandex.net/v1/disk/public/resources/download?public_key={public_key}&path={item['path']}"
                        dl_response = requests.get(download_url)
                        
                        if dl_response.status_code == 200:
                            file_url = dl_response.json().get('href')
                            size_mb = item.get('size', 0) / (1024 * 1024)
                            
                            videos.append({
                                'name': filename,
                                'url': file_url,
                                'size_mb': round(size_mb, 2)
                            })
                            
                            print(f"     ✓ Added ({size_mb:.1f} MB)")
        
        return videos
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return []

def save_playlist(videos, filename="playlist.m3u8"):
    """Save video links as m3u8 playlist"""
    if not videos:
        print("❌ No videos to save")
        return
    
    with open(filename, 'w') as f:
        f.write("#EXTM3U\n")
        f.write("#EXT-X-VERSION:3\n")
        f.write(f"# Generated by Yandex m3u8 Extractor\n")
        f.write(f"# Date: {datetime.now()}\n\n")
        
        for video in videos:
            f.write(f"#EXTINF:-1,{video['name']} ({video['size_mb']} MB)\n")
            f.write(f"{video['url']}\n")
    
    print(f"\n✅ Saved {len(videos)} videos to {filename}")

def main():
    if len(sys.argv) < 2:
        print("📖 Usage: python extractor.py <yandex_url>")
        print("📝 Example: python extractor.py https://yadi.sk/d/abc123")
        print("\n📌 The URL should be a public Yandex.Disk link")
        sys.exit(1)
    
    url = sys.argv[1]
    videos = extract_from_yandex(url)
    
    if videos:
        print(f"\n📊 Summary:")
        for v in videos:
            print(f"  • {v['name']} ({v['size_mb']} MB)")
        save_playlist(videos)
        print(f"\n✨ Done! You can now use playlist.m3u8 in your video player")
    else:
        print("\n❌ No videos found")

if __name__ == "__main__":
    main()
